### ISSUE TITLE
Which version of PsychoPy was this written for? 

### ISSUE THREAD

**Issue by csteacherd22** [ianhussey/IRAP#6]
I've been getting some errors and I'm not sure if I should be tweaking PsychoPy to work with IRAP or vice versa. 
Currently, I'm running PsychoPy 1.83.04. Running IRAP shows a few deprecation warnings but then crashes on some index value. 
```
Traceback (most recent call last):
  File "Open Source IRAP.py", line 595, in <module>
    for thisTask in task:
  File "/usr/lib/python2.7/dist-packages/psychopy/data.py", line 951, in next
    self.data.add('ran',1)
  File "/usr/lib/python2.7/dist-packages/psychopy/data.py", line 3618, in add
    self[thisType][position[0],position[1]]=value
  File "/usr/local/lib/python2.7/dist-packages/numpy/ma/core.py", line 3399, in __setitem__
    _data[indx] = dval
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by ianhussey** [comment]
If you check out the readme you'll see that it was written in PsychoPy 1.82 and that later versions throw errors. I haven't updated it for compatibility beyond this version, but feel free to make a pull request if you do the necessary changes.

**Comment by csteacherd22** [comment]
Thank you. I missed that.
